pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: helm
                image: lachlanevenson/k8s-helm:v3.10.2
                command:
                - cat
                tty: true
            """
        }
    }

    stages {
        stage('Install Helm') {
            steps {
                sh '''
                curl -LO https://get.helm.sh/helm-v3.18.4-linux-amd64.tar.gz
                tar -zxvf helm-v3.18.4-linux-amd64.tar.gz
                mv linux-amd64/helm ./helm
                chmod +x ./helm
                '''
            }
        }

        stage('Add Helm Repos') {
            steps {
                container('helm') {
                    sh '''
                    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                    helm repo add grafana https://grafana.github.io/helm-charts
                    helm repo update
                    '''
                }
            }
        }

        stage('Create Namespace') {
            steps {
                container('helm') {
                    sh 'kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -'
                }
            }
        }

        stage('Deploy Prometheus') {
            steps {
                container('helm') {
                    sh '''
                    helm upgrade --install my-prometheus prometheus-community/prometheus \
                    --namespace monitoring \
                    --values prometheus-values.yaml
                    '''
                }
            }
        }

        stage('Deploy Grafana') {
            steps {
                container('helm') {
                    sh '''
                    helm upgrade --install my-grafana grafana/grafana \
                    --namespace monitoring \
                    --values grafana-values.yaml
                    '''
                }
            }
        }
    }
}