pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              serviceAccountName: jenkins
              containers:
              - name: helm
                image: lachlanevenson/k8s-helm:v3.10.2
                command:
                - cat
                tty: true
              - name: kubectl
                image: bitnami/kubectl:1.33
                command:
                - cat
                tty: true
            """
        }
    }
    
    stages {
        stage('Create Namespace') {
            steps {
                container('kubectl') {
                    sh '''
                        cat <<EOF | kubectl apply -f -
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                        name: monitoring
                        EOF
                    '''
                }
            }
        }

        stage('Add Helm Repos') {
            steps {
                container('helm') {
                    sh '''
                    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                    helm repo add grafana https://grafana.github.io/helm-charts
                    helm repo update
                    '''
                }
            }
        }

        stage('Deploy Prometheus') {
            steps {
                container('helm') {
                    sh '''
                    helm upgrade --install my-prometheus prometheus-community/prometheus \
                    --namespace monitoring \
                    --values prometheus-values.yaml
                    '''
                }
            }
        }

        stage('Deploy Grafana') {
            steps {
                container('helm') {
                    sh '''
                    helm upgrade --install my-grafana grafana/grafana \
                    --namespace monitoring \
                    --values grafana-values.yaml
                    '''
                }
            }
        }
    }
}