{
 "title": "MyMinikubeDashbord",
 "time": { "from": "2025-07-24T10:58:17.639Z", "to": "2025-07-24T11:03:46.838Z" },
 "panels": [
  {
   "title": "Minikube Used Memory in bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minikube Total CPU Usage in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"kube-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins pod (server and agent) Used Memory in bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"jenkins-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins pod (server and agent) Total CPU Usage in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"jenkins-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APP pod Used Memory in bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"release-1-my-chart-85c54f7cd4-9k9g5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APP pod Total CPU Usage in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"release-1-my-chart-85c54f7cd4-9k9g5\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}