pipeline {
    agent any

    triggers {
        pollSCM('H/1 * * * *') 
    }

    stages {
         stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/gantsevich-yuri/rsschool-devops-course-tasks.git',
                    branch: 'task_6',
                    credentialsId: 'github-token'
                )
            }
        }

        stage('Build App') {
            steps {
                //sh 'apt install python3-pip'
                //sh 'pip install --upgrade pip setuptools && pip install -r requirements.txt'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test App') {
            steps {
                sh 'pytest test.py'
            }
        }
        /*
        stage('SonarQube test') {
            //
        }

        stage('Docker biuld') {
            steps {
                sh 'docker build ./my-app/ -t my-flask-app:v$BUILD_NUMBER'
            }
        }
        */
    }
}
