pipeline {
    triggers {
        pollSCM('H/1 * * * *') 
    }

    tools {
        sonarQube 'SonarScanner'
    }

    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
                - name: jnlp
                  image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-6

                - name: python
                  image: python:3.13
                  command: ["cat"]
                  tty: true

                - name: docker
                  image: docker:28
                  command: ["cat"]
                  tty: true
                  volumeMounts:
                    - name: docker-sock
                      mountPath: /var/run/docker.sock
              volumes:
                - name: docker-sock
                  hostPath:
                    path: /var/run/docker.sock
                    type: Socket
            """
        }
    }

    stages {
         stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/gantsevich-yuri/rsschool-devops-course-tasks.git',
                    branch: 'task_6',
                    credentialsId: 'github-token'
                )
            }
        }

        stage('Build App') {
            steps {
                container('python') {
                    sh 'pip install -r deployment/my-app/requirements.txt --break-system-packages'
                }
            }
        }

        stage('Test App') {
            steps {
                container('python') {
		            dir('deployment/my-app') {
                        sh 'pytest test.py'
	                }
                }
            }
        }
        
        stage('SonarQube test') {
            steps {
                container('python') {
                    withSonarQubeEnv('jenkins-sonar') {
                        sh '''
                            apt update && apt install -y unzip wget
                            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
                            unzip sonar-scanner-cli-*.zip
                            mv sonar-scanner-* sonar-scanner
                            ./sonar-scanner/bin/sonar-scanner \
                                -Dsonar.projectKey=jenkins-sonar \
                                -Dsonar.sources=deployment/my-app
                        '''
                    }
                }
            }
}
        /*
        stage('Docker biuld') {
            steps {
                container('docker') {
		            dir('deployment/my-app') {
                        sh 'docker build . -t my-flask-app:v$BUILD_NUMBER'
		            }
                }
            }
        }
    */
    }
}